
services:
  postgres:
    image: postgres:13
    container_name: Metadata_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432" # Expose PostgreSQL on port your choice
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/infrastructure/db/migrations/metadata.sql:/docker-entrypoint-initdb.d/metadata.sql:ro
      #si tienes problemas puedes eliminar el volumen docker-compose down -v
      # reiniciarlo docker-compose up --build
    restart: unless-stopped

volumes:
  postgres_data:
