CREATE TABLE documentos_clasificados (
    id SERIAL PRIMARY KEY,
    ruc_encontrado VARCHAR(13) NOT NULL,
    razon_social TEXT NOT NULL,
    estado_contribuyente_ruc VARCHAR(50) NOT NULL,
    actividad_economica_principal TEXT NOT NULL,
    tipo_contribuyente VARCHAR(50) NOT NULL,
    regimen VARCHAR(50) NOT NULL,
    categoria VARCHAR(50),
    obligado_llevar_contabilidad VARCHAR(2) NOT NULL,
    agente_retencion VARCHAR(2) NOT NULL,
    contribuyente_especial VARCHAR(2) NOT NULL,
    fecha_inicio_actividades VARCHAR(50) NOT NULL,
    fecha_cese VARCHAR(50),
    fecha_reinicio_actividades VARCHAR(50),
    fecha_actualizacion VARCHAR(50) NOT NULL,
    representante_identificacion VARCHAR(20) NOT NULL,
    representante_nombre TEXT NOT NULL,
    motivo_cancelacion_suspension TEXT,
    contribuyente_fantasma VARCHAR(2) NOT NULL,
    transacciones_inexistente VARCHAR(2) NOT NULL,
    clasificacion_legal TEXT,
    clasificacion_tecnica TEXT,
    clasificacion_economica TEXT,
    texto_pdf_completo TEXT NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
